spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
    ddl-auto: update
  properties.hibernate.format_sql: true
  show-sql: true
spring:
  datasource:
    hikari:
      maximum-pool-size: 4
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-44-210-50-83.compute-1.amazonaws.com/dfrur30gf9g5al
    username: tmxrdkrhqqempi
    password: 67450372a352df96b947edd683b4dbb8bc465922f091968ce3bae657290cde7f
    platform: postgres
  redis:
    port: 6379
    host: 192.168.0.2
    url:
  kafka:
    properties:
    consumer:
      bootstrap-servers:
      group-id: alarm
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: *
    listener:
      ack-mode: MANUAL
    producer:
      bootstrap-servers:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topic:
      alarm: alarm


jwt:
  secret-key : jaypark.sns-application-2022.secret_key
#  30day
  token.expired-time-ms : 259200000
