spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
    ddl-auto: create-drop
  properties.hibernate.format_sql: true
  show-sql: true
spring:
  datasource:
    hikari:
      maximum-pool-size: 4
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-44-210-50-83.compute-1.amazonaws.com/dfrur30gf9g5al
    username: tmxrdkrhqqempi
    password: 67450372a352df96b947edd683b4dbb8bc465922f091968ce3bae657290cde7f
    platform: postgres

jwt:
  secret-key : jaypark.sns-application-2022.secret_key
#  30day
  token.expired-time-ms : 259200000

